/*
  This file is part of SystemBurn.

  Copyright (C) 2012, UT-Battelle, LLC.

  This product includes software produced by UT-Battelle, LLC under Contract No. 
  DE-AC05-00OR22725 with the Department of Energy. 

  This program is free software; you can redistribute it and/or modify
  it under the terms of the New BSD 3-clause software license (LICENSE). 
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
  LICENSE for more details.

  For more information please contact the SystemBurn developers at: 
  systemburn-info@googlegroups.com

*/
#include "brand.h"

/**
 * \brief Gives a 'random' value
 * \param p The struct that holds the information for brand.
 * \return ret The 'random' number
 * \sa brand_init
 * \sa rfraction
 */
uint64_t brand (brand_t *p) {
	uint64_t hi=p->hi, lo=p->lo, i=p->ind, ret;

	ret = p->tab[i];

	_BR_64STEP_(hi,lo,45,118);

	p->tab[i] = ret + hi;

	p->hi  = hi;
	p->lo  = lo;
	p->ind = hi & _maskr(_BR_LG_TABSZ_);

	return ret;
}

/**
 * \brief Initializes the values for creating a 'random' int
 * \param p The struct that holds the information for brand.
 * \param val The initialization value.
 * \sa brand
 */
void brand_init (brand_t *p, uint64_t val) {
	int64_t i;
	uint64_t hi, lo;

	hi = 0x9ccae22ed2c6e578uL ^ val;
	lo = 0xce4db5d70739bd22uL & _maskl(118-64);

	for (i = 0; i < 64; i++)
	_BR_64STEP_(hi,lo,33,118);

	for (i = 0; i < _BR_TABSZ_; i++) {
	_BR_64STEP_(hi,lo,33,118);
	p->tab[i] = hi;
	}
	p->ind = (uint64_t)(_BR_TABSZ_/2);
	p->hi  = hi;
	p->lo  = lo;

	for (i = 0; i < _BR_RUNUP_; i++)
	(void)brand(p);
}

/**
 * \brief Gives a random fraction
 * \return double Returns the random fraction, generated by brand
 * \param p The struct that holds the information for brand.
 * \sa brand
 */
// A random fraction
double rfraction(brand_t *p){
	return  ( (double)(brand(p) & ((1L << 50) - 1)) ) /
		(double)((1L << 50) - 1);
}

