#!/bin/sh
#  This file is part of SystemBurn.
#
#  Copyright (C) 2012, UT-Battelle, LLC.
#
#  This product includes software produced by UT-Battelle, LLC under Contract No. 
#  DE-AC05-00OR22725 with the Department of Energy. 
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the New BSD 3-clause software license (LICENSE). 
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
#  LICENSE for more details.
#
#  For more information please contact the SystemBurn developers at: 
#  systemburn-info@googlegroups.com

mv -f orbtconfig.h orbtconfig.old 2>/dev/null

case ${1} in
	x86cluster)
		echo "/* Generated by orbtconfig.sh */"		>  orbtconfig.h
		echo "#ifndef ORB_TIMER_CONFIG"			>> orbtconfig.h
		echo "#define ORB_TIMER_CONFIG"			>> orbtconfig.h
		echo "#define TIMER_X86_64"			>> orbtconfig.h
		echo "#define NODEID_GETHOSTNAME"		>> orbtconfig.h
		echo "#endif"                 			>> orbtconfig.h
		: ;;
	crayxt)
		echo "/* Generated by orbtconfig.sh */" 	>  orbtconfig.h
		echo "#ifndef ORB_TIMER_CONFIG"			>> orbtconfig.h
		echo "#define ORB_TIMER_CONFIG"			>> orbtconfig.h
		echo "#define TIMER_X86_64"			>> orbtconfig.h
		echo "#define NODEID_MPI"			>> orbtconfig.h
		echo "#endif"					>> orbtconfig.h
		: ;;
	ibmbgp)
		echo "/* Generated by orbtconfig.sh */"		>  orbtconfig.h
		echo "#ifndef ORB_TIMER_CONFIG"			>> orbtconfig.h
		echo "#define ORB_TIMER_CONFIG"			>> orbtconfig.h
		echo "#define TIMER_MPI_WTIME"			>> orbtconfig.h
		echo "#define NODEID_MPI"			>> orbtconfig.h
		echo "#endif"					>> orbtconfig.h
		: ;;
	sicortex)
		echo "/* Generated by orbtconfig.sh */"		>  orbtconfig.h
		echo "#ifndef ORB_TIMER_CONFIG"			>> orbtconfig.h
		echo "#define ORB_TIMER_CONFIG"			>> orbtconfig.h
		echo "#define TIMER_MPI_WTIME"			>> orbtconfig.h
		echo "#define NODEID_SLURM"			>> orbtconfig.h
		echo "#endif"					>> orbtconfig.h
		: ;;
	power7)
		echo "/* Generated by orbtconfig.sh */"		>  orbtconfig.h
		echo "#ifndef ORB_TIMER_CONFIG"			>> orbtconfig.h
		echo "#define ORB_TIMER_CONFIG"			>> orbtconfig.h
		echo "#define TIMER_PPC64"			>> orbtconfig.h
		echo "#define NODEID_MPI"			>> orbtconfig.h
		echo "#endif"					>> orbtconfig.h
		: ;;
	*)
		echo "Usage: $0 <target>"
		echo "  valid values for target are:"
		echo "    x86cluster -- generic x86-64 (x86-64 timers and gethostname node-ids)"
		echo "    crayxt     -- Cray XT        (x86-64 timers and MPI node-ids)"
		echo "    ibmbgp     -- IBM BG/P       (MPI timers and MPI node-ids)"
		echo "    sicortex   -- SiCortex       (MPI timers and SLURM node-ids)"
		echo "    power7     -- IBM Power7     (MPI timers and MPI node-ids)"
		: ;;
esac
	
